server:
  port: 8082

spring:
  application:
    name: service-2

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411

service3.url: http://service-3:8083

logging.level.org.springframework.cloud.sleuth: DEBUG